### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/Build-responsive-design#4]
Feel free to leave some comments

**Comment by nyatindopatrick** [comment]
Good job! 

- To fix the responsiveness of your article preview images in mobile view try adjusting your grid to look like this:

```
@media only screen and (max-width: 767px)
.article-preview {
    grid-template-columns: 6fr 2fr;
    height: auto;
}
```

- Try this fix also with ".second-section article"  in mobile view:
```
@media only screen and (max-width: 767px)
.second-section article, .fifth-section article {
    grid-column: 1 / span 3;
    display: grid;
    grid-template-columns: 20% 1fr;
    grid-gap: 15px;
}
```

**Comment by Kyle-Law** [comment]
Great. Nothing huge to complain about. Everything looks decent. Below is some tiny refinement that I could find:
- At smaller screen below 767px, 'See More' is actually come before 'Add info' at the Latest funding section. It could be achieved using the `order` property of the flexbox. But it won't be an issue if Maria is not your code reviewer haha

That's all for me. Great job @patriciachrysy  :)

**Comment by dili021** [comment]
Here are my suggestions:
-give the .second-section images a min-width instead of regular width of 100% (which doesn't do anything in this case) so they stop shrinking at a certain point. Since you are using grid you can also use minmax().
-You can use word-wrap for the max-width(768px) screen size so that the text behaves more like the original. Combined with a fixed img size I think this will fix your breaking problem.
.Same img problem with the third and fourth (just the smaller images) section.
-On a second look at the original, it's not even min-width, it's just a fixed width of 75px
-If you are going to go into full detail with regards to cloning the actual responsiveness, then the footer icons are also behaving a bit differently.

Other than this, and the minor padding/margin fixes I think it is spot on. Good job!

**Comment by patriciachrysy** [comment]
Thank you guys for your suggestions
